-- CreateTable
CREATE TABLE `Weapon` (
    `weapon_id` INTEGER NOT NULL AUTO_INCREMENT,
    `bng_weapon_id` BIGINT UNSIGNED NOT NULL,
    `weapon_name` VARCHAR(255) NOT NULL,
    `weapon_type` ENUM('SIDEARM', 'HAND_CANNON', 'AUTO_RIFLE', 'PULSE_RIFLE', 'COMBAT_BOW', 'SUBMACHINE_GUN', 'SCOUT_RIFLE', 'SNIPER_RIFLE', 'SHOTGUN', 'GLAIVE', 'GRENADE_LAUNCHER', 'TRACE_RIFLE', 'FUSION_RIFLE', 'MACHINE_GUN', 'ROCKET_LAUNCHER', 'LINEAR_FUSION_RIFLE', 'SWORD') NOT NULL DEFAULT 'AUTO_RIFLE',
    `ammo_type` ENUM('PRIMARY', 'SPECIAL', 'HEAVY') NOT NULL DEFAULT 'PRIMARY',
    `slot` ENUM('KINETIC', 'ENERGY', 'POWER') NOT NULL DEFAULT 'KINETIC',
    `damage_type` ENUM('KINETIC', 'ARC', 'SOLAR', 'VOID', 'STASIS', 'STRAND') NOT NULL DEFAULT 'KINETIC',
    `rarity` ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'EXOTIC') NOT NULL DEFAULT 'COMMON',

    UNIQUE INDEX `Weapon_bng_weapon_id_key`(`bng_weapon_id`),
    PRIMARY KEY (`weapon_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Armor` (
    `armor_id` INTEGER NOT NULL AUTO_INCREMENT,
    `bng_armor_id` BIGINT UNSIGNED NOT NULL,
    `armor_name` VARCHAR(255) NOT NULL,
    `slot` ENUM('HELMET', 'GAUNTLETS', 'CHEST', 'BOOTS', 'CLASS_ITEM') NOT NULL DEFAULT 'CLASS_ITEM',
    `rarity` ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'EXOTIC') NOT NULL DEFAULT 'COMMON',

    UNIQUE INDEX `Armor_bng_armor_id_key`(`bng_armor_id`),
    PRIMARY KEY (`armor_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
